POST https://pretix.eu/api/v1/organizers/taz-zuzalu/events/event-series/vouchers/
Host: pretix.eu
Accept: application/json, text/javascript
Content-Type: application/json

{
  "code": "43K6LKM37FBVR2YG",
  "max_usages": 1,
  "valid_until": null,
  "block_quota": false,
  "allow_ignore_quota": false,
  "price_mode": "set",
  "value": "0",
  "item": 1,
  "variation": null,
  "quota": null,
  "tag": "testvoucher",
  "comment": "",
  "subevent": null
}