POST https://pretix.eu/api/v1/organizers/taz-zuzalu/events/test-zuzalu-3/quotas/
Host: pretix.eu
Authorization: Token h074quiq51d5xwk55tax7t7an12v3bb1rbdvk16209fsf4d1tqqtg9o68yy5jgmz
Accept: application/json, text/javascript
Content-Type: application/json

{
  "name": "Ticket Quota Zuzalu-3",
  "size": 200,
  "items": [316436],
  "variations": [133240, 133241],
  "subevent": null,
  "close_when_sold_out": false,
  "closed": false
}