POST https://pretix.eu/api/v1/organizers/taz-zuzalu/events/gym-muay-thai/quotas/
Host: pretix.eu
Authorization: Token gqmo1r79hsljkjv2dcr9pgo93x6aj4dzbflxgq4fdmrdc7tjh99fc4quhf8tju9i
Accept: application/json, text/javascript
Content-Type: application/json

{
  "name": "Ticket Quota Gym Muay Thai",
  "size": 200,
  "items": [317913],
  "variations": [],
  "subevent": null,
  "close_when_sold_out": false,
  "closed": false
}
